// Generated by eve. Do not edit by hand.

import * as module_0 from "../../../agent/agent.ts";
import * as module_1 from "../../../agent/channels/eve.ts";
import * as module_2 from "../../../agent/tools/fetch_multas_rosario.ts";
import * as module_3 from "../../../agent/tools/get_patente_status.ts";
import * as module_4 from "../../../agent/tools/list_multas.ts";
import * as module_5 from "../../../agent/tools/pay_multa.ts";
import * as module_6 from "../../../agent/tools/pay_patente.ts";
import * as module_7 from "../../../agent/tools/scan_gmail_multas.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/eve.ts": module_1,
                  "tools/fetch_multas_rosario.ts": module_2,
                  "tools/get_patente_status.ts": module_3,
                  "tools/list_multas.ts": module_4,
                  "tools/pay_multa.ts": module_5,
                  "tools/pay_patente.ts": module_6,
                  "tools/scan_gmail_multas.ts": module_7
                })
            })
    })
});

export default moduleMap;
